### ISSUE TITLE
Installationanleitung sysml version

### ISSUE THREAD

**Issue by Marcus-22** [PeterReichenpfader/ALKS-Repo#1]
Hi Peter,

leider bin ich bei dem Versuch mir eine Eclispe + Papyrus + SysML Konfiguration zu erstellen gescheitert.
In der Installationsanleitung wird ein Executable für die Eclipese Installation genannt. 
Das ist der Eclipse Installer oder? 
Welche Eclispe Variante muss man dann verwenden? Java oder Modeling? 
Welche Version: Latest and Greates oder Aktuelles Release (das wäre 12 2020.)
Welche Papyrus-Version 5.0.0?
Die habe ich aber leider weder mit SysML 1.4 bzw. SysML 1.6 zum Laufen gebracht.
Kannst Du bitte noch angegeben wie Du das SysML-Profil installiert hast.
Danke!
Gruß
Marcus

**Comment by Marcus-22** [comment]
Ich habe nun eine funktionierende SysMl1.4 Papyrus Konfiguration:

Eclipse Modeling Tools
Version: 2020-06 (4.16.0)

Papyrus UML Modeler 4.8
Papyrus SysML 1.4 UI  1.3.200

Der Versuch mit akuellen Eclipse Release (12 2020) + aktuelles Papyrus Release (5.0.0.) SysML 1.4 zum Laufen zu bringen scheitert bei mir ...

**Comment by jdsika** [comment]
Die Anleitung sollte ebenfalls für Windows und Linux zur Verfügung gestellt werden. Sprache sollte .generell Englisch sein. Eine Pfansangabe ist noch personalisiert "C:\Users\peterreichenpfader". Für alle Softwarekomponenten sollten minimal Versionen angegeben werden, mit welchen der Setup getestet wurde. Für alle Softwarekomponenten sollte es entweder ein automatisiertes Skript zur Installation oder direkte Downloadlinks mit zB Kommandozeilen anweisungenn (copy&paste) zum editieren von Dateien etc geben

**Comment by jdsika** [comment]
In der Papyrus installationsanleitung sollte auch kein fester Pfad stehen sondern eine variable [Link](https://stackoverflow.com/questions/52511778/how-to-install-openjdk-11-on-windows):
`%JAVA_HOME%\bin`

Papyrus Installation:
Help -> Install new software
In the "Work with" section of "Available Software", select the release of interest (e.g., Neon)
In the type filter, type "Papyrus"
Select "Papyrus UML" and, optionally, the model comparison feature.
Select [Next]
Select [Next] again to the details
Accept the licenses and click [Finish].
Enjoy modeling!

Then "open perspective "papyrus" and open the project. Then the following error occurs:
![grafik](https://user-images.githubusercontent.com/11943343/109470597-eeb91e80-7a6f-11eb-8ad4-5ab7e7be2721.png)
